app:
  telegram-token: ${TELEGRAM_TOKEN} # env variable
  scrapper-url: http://localhost:8081
  message-transport: http


spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8080

kafka:
  topic: notifications


springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
